HomeWork #28: File transfer over HTTP
safgbad/skypro_homework pull request #43
Opened 2023-02-06 12:16 UTC by safgbad

2023-02-06 19:22 UTC, alekseykoshelev requested changes

2023-02-06 19:22 UTC, alekseykoshelev commented on src/main/java/pro/sky/course3/hw24/contollers/FilesController.java
> +        if (dataFileName == null) return ResponseEntity.badRequest().build();
Тут бы лучше скобки добавить фигурные.

2023-02-06 19:22 UTC, alekseykoshelev commented on src/main/java/pro/sky/course3/hw24/contollers/FilesController.java
> +            case "ingredient" -> IngredientsServiceImpl.INGREDIENTS_DATA_FILE_NAME;
Лучше вместо статических переменных вызвать метод у сервиса

2023-02-06 19:22 UTC, alekseykoshelev commented on src/main/java/pro/sky/course3/hw24/services/impl/IngredientsServiceImpl.java
> +    private void setIngredientsDataFileName(String ingredientsDataFileName) {
Прошлый вариант был лучше, почему он тебе не понравился?

2023-02-06 20:45 UTC, safgbad commented on src/main/java/pro/sky/course3/hw24/contollers/FilesController.java
> +        if (dataFileName == null) return ResponseEntity.badRequest().build();
добавил в двух местах

2023-02-06 20:53 UTC, safgbad commented on src/main/java/pro/sky/course3/hw24/services/impl/IngredientsServiceImpl.java
> +    private void setIngredientsDataFileName(String ingredientsDataFileName) {
Перенес все имена файлов в FilesService, доступ к ним через геттеры.
Изначально хотел, чтобы имена файлов лежали в соответствующих сервисах. А если они не статик, то для доступа к ним из других сервисов пришлось бы делать отдельное поле только для того, чтобы геттер можно было вызвать (например поле ingredientsService в RecipesServiceImpl).
Где-то услышал, что плохо когда сервисы друг в друга ходят. И меня всё это смущает. Надеюсь сейчас ок.

2023-02-07 19:41 UTC, alekseykoshelev commented on src/main/java/pro/sky/course3/hw24/services/impl/IngredientsServiceImpl.java
> +    public Map<Integer, Ingredient> ingredients = new LinkedHashMap<>();
Лучше сделать `private`

2023-02-07 19:41 UTC, alekseykoshelev commented on src/main/java/pro/sky/course3/hw24/util/Utils.java
> +        Collection<Ingredient> ingredients = ingredientsService.getIngredients().values();
Этот метод немного странный, учитывая, что сюда нужно передавать сервис ингредиентов. Лучше это перенести в один из сервисов, в рецепты или ингредиенты.

2023-02-23 04:59 UTC, merged